<a href="https://colab.research.google.com/github/FRashidy1403/Special/blob/main/chapter6_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 6.6

In [1]:
from nltk.stem.porter import PorterStemmer
# Create word tokens
tokenized_words = [ 'i' , 'am' , 'humbled' , 'by' , 'this' , 'traditional' , 'meeting' ]
# Create stemmer
porter = PorterStemmer ()
# Apply stemmer
[ porter . stem ( word ) for word in tokenized_words ]

['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

# 6.7

In [6]:
import nltk
# nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.


True

In [7]:
# Load libraries
from nltk import pos_tag
from nltk import word_tokenize
# Create text
text_data = "Chris loved outdoor running"
# Use pretrained part of speech tagger
text_tagged = pos_tag ( word_tokenize ( text_data ))
# Show parts of speech
text_tagged
# Filter words
[ word for word , tag in text_tagged if tag in [ 'NN' , 'NNS' , 'NNP' , 'NNPS' ] ]

['Chris']

In [8]:
from nltk import pos_tag
from nltk import word_tokenize
from sklearn.preprocessing import MultiLabelBinarizer
# Create text
tweets = [ "I am eating a burrito for breakfast" ,
"Political science is an amazing field" ,
"San Francisco is an awesome city" ]
# Create list
tagged_tweets = []
# Tag each word and each tweet
for tweet in tweets :
  tweet_tag = nltk . pos_tag ( word_tokenize ( tweet ))
  tagged_tweets . append ([ tag for word , tag in tweet_tag ])
# Use one-hot encoding to convert the tags into features
one_hot_multi = MultiLabelBinarizer ()
one_hot_multi . fit_transform ( tagged_tweets )
# Show feature names
one_hot_multi . classes_

array(['DT', 'IN', 'JJ', 'NN', 'NNP', 'PRP', 'VBG', 'VBP', 'VBZ'],
      dtype=object)

#6.8

In [9]:
# Import libraries
import spacy
# Load the spaCy package and use it to parse the text
# make sure you have run "python -m spacy download en"
nlp = spacy . load ( "en_core_web_sm" )
doc = nlp ( "Elon Musk offered to buy Twitter using $21B of his own money." )
# Print each entity
print ( doc . ents )
# For each entity print the text and the entity label
for entity in doc . ents :
  print( entity . text , entity . label_ , sep= "," )

(Elon Musk, Twitter, 21B)
Elon Musk,PERSON
Twitter,PERSON
21B,MONEY


# 6.9

In [10]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
# Create text
text_data = np . array ([ 'I love Brazil. Brazil!' ,
'Sweden is best' ,
'Germany beats both' ])
# Create the bag of words feature matrix
count = CountVectorizer ()
bag_of_words = count . fit_transform ( text_data )
# Show feature matrix
bag_of_words

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (3, 8)>

In [11]:
bag_of_words . toarray ()

array([[0, 0, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0]])

In [12]:
count . get_feature_names_out ()

array(['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love',
       'sweden'], dtype=object)

In [13]:
count_2gram = CountVectorizer ( ngram_range= ( 1 , 2 ),
                                stop_words= "english" ,
                                vocabulary= [ 'brazil' ])
bag = count_2gram . fit_transform ( text_data )
# View feature matrix
bag . toarray ()

array([[2],
       [0],
       [0]])

In [14]:
count_2gram . vocabulary_

{'brazil': 0}

# 6.10

In [15]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
# Create text
text_data = np . array ([ 'I love Brazil. Brazil!' ,
'Sweden is best' ,
'Germany beats both' ])
# Create the tf-idf feature matrix
tfidf = TfidfVectorizer ()
feature_matrix = tfidf . fit_transform ( text_data )
# Show tf-idf feature matrix
feature_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 8 stored elements and shape (3, 8)>

In [16]:
feature_matrix . toarray ()

array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

In [17]:
tfidf . vocabulary_

{'love': 6,
 'brazil': 3,
 'sweden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}

# 6.11

In [19]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
# Create searchable text data
text_data = np . array ([ 'I love Brazil. Brazil!' ,
'Sweden is best' ,
'Germany beats both' ])
# Create the tf-idf feature matrix
tfidf = TfidfVectorizer ()
feature_matrix = tfidf . fit_transform ( text_data )
# Create a search query and transform it into a tf-idf vector
text = "Brazil is the best"
vector = tfidf . transform ([ text ])

In [22]:
vector

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3 stored elements and shape (1, 8)>

In [24]:
cosine_similarities = linear_kernel ( vector , feature_matrix ) . flatten ()
# Get the index of the most relevent items in order
related_doc_indicies = cosine_similarities . argsort ()[: - 10 : - 1 ]
# Print the most similar texts to the search query along with the cosine
# similarity
print ([( text_data [ i ], cosine_similarities [ i ]) for i in related_doc_indicies ])

[(np.str_('Sweden is best'), np.float64(0.6666666666666666)), (np.str_('I love Brazil. Brazil!'), np.float64(0.5163977794943222)), (np.str_('Germany beats both'), np.float64(0.0))]


# 6.12

In [25]:
from transformers import pipeline
# Create an NLP pipeline that runs sentiment analysis
classifier = pipeline ( "sentiment-analysis" )
# Classify some text
# (this may download some data and models the first time you run it)
sentiment_1 = classifier ( "I hate machine learning! It's the absolute worst." )
sentiment_2 = classifier (
"Machine learning is the absolute"
"bees knees I love it so much!"
)
# Print sentiment output
print ( sentiment_1 , sentiment_2 )

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cpu


[{'label': 'NEGATIVE', 'score': 0.9998020529747009}] [{'label': 'POSITIVE', 'score': 0.9995730519294739}]


# 13.1

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
# Generate features matrix, target vector
features , target = make_regression ( n_samples = 100 ,
n_features = 3 ,
n_informative = 2 ,
n_targets = 1 ,
noise = 0.2 ,
coef = False ,
random_state = 1 )
# Create linear regression
regression = LinearRegression ()
# Fit the linear regression
model = regression . fit ( features , target )

In [ ]:
model . intercept_

In [ ]:
model . coef_

In [ ]:
target [ 0 ]

In [ ]:
model . predict ( features )[ 0 ]

# 13.2

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression
# Generate features matrix, target vector
features , target = make_regression ( n_samples = 100 ,
n_features = 2 ,
n_informative = 2 ,
n_targets = 1 ,
noise = 0.2 ,
coef = False ,
random_state = 1 )
# Create interaction term
interaction = PolynomialFeatures (
degree=3 , include_bias=False , interaction_only=True )
features_interaction = interaction . fit_transform ( features )
# Create linear regression
regression = LinearRegression ()
# Fit the linear regression
model = regression . fit ( features_interaction , target )

In [ ]:
features [ 0 ]

In [ ]:
# Import library
import numpy as np
# For each observation, multiply the values of the first and second feature
interaction_term = np . multiply ( features [:, 0 ], features [:, 1 ])
We can then view the interaction term for the first observation:
# View interaction term for first observation
interaction_term [ 0 ]

In [ ]:
features_interaction [ 0 ]

# 13.3

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_regression
# Generate features matrix, target vector
features , target = make_regression ( n_samples = 100 ,
n_features = 3 ,
n_informative = 2 ,
n_targets = 1 ,
noise = 0.2 ,
coef = False ,
random_state = 1 )
# Create polynomial features x^2 and x^3
polynomial = PolynomialFeatures ( degree=3 , include_bias=False )
features_polynomial = polynomial . fit_transform ( features )
# Create linear regression
regression = LinearRegression ()
# Fit the linear regression
model = regression . fit ( features_polynomial , target )


In [ ]:
features [ 0 ]

In [ ]:
features [ 0 ] **2

In [ ]:
features [ 0 ] **3

In [ ]:
features_polynomial [ 0 ]

# 13.4

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression
# Generate features matrix, target vector
features , target = make_regression ( n_samples = 100 ,
n_features = 3 ,
n_informative = 2 ,
n_targets = 1 ,
noise = 0.2 ,
coef = False ,
random_state = 1 )
# Standardize features
scaler = StandardScaler ()
features_standardized = scaler . fit_transform ( features )

In [ ]:
# Create ridge regression with an alpha value
regression = Ridge ( alpha=0.5 )
# Fit the linear regression
model = regression . fit ( features_standardized , target )

In [ ]:
# Load library
from sklearn.linear_model import RidgeCV
# Create ridge regression with three alpha values
regr_cv = RidgeCV ( alphas= [ 0.1 , 1.0 , 10.0 ])
# Fit the linear regression
model_cv = regr_cv . fit ( features_standardized , target )
# View coefficients
model_cv . coef_

In [ ]:
model_cv . alpha_

# 13.5

In [ ]:
# Load library
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_regression
# Generate features matrix, target vector
features , target = make_regression ( n_samples = 100 ,
n_features = 3 ,
n_informative = 2 ,
n_targets = 1 ,
noise = 0.2 ,
coef = False ,
random_state = 1 )
# Standardize features
scaler = StandardScaler ()
features_standardized = scaler . fit_transform ( features )

In [ ]:
# Create lasso regression with alpha value
regression = Lasso ( alpha=0.5 )
# Fit the linear regression
model = regression . fit ( features_standardized , target )

In [ ]:
model . coef_

In [ ]:
# Create lasso regression with a high alpha
regression_a10 = Lasso ( alpha=10 )
model_a10 = regression_a10 . fit ( features_standardized , target )
model_a10 . coef_