In [1]:
import numpy as np
from scipy import sparse

In [2]:

matrix_large = np . array ([[ 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ],
                            [ 0 , 1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ],
                            [ 3 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ]])

matrix_large_sparse = sparse . csr_matrix ( matrix_large )
# print ( matrix_sparse )
print ( matrix_large_sparse )


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [3]:
vector = np . array ([ 1 , 2 , 3 , 4 , 5 , 6 ])

matrix = np . array ([[ 1 , 2 , 3 ],
[ 4 , 5 , 6 ],
[ 7 , 8 , 9 ]])

print(vector [ 2 ])
print(matrix [ 1 , 1 ])

3
5


In [8]:
print(vector [:])

print(vector [: 3 ])

print(vector [ 3 :])

print(vector [ - 1 ])
print(matrix [: 2 ,:])


[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]


In [9]:
matrix [:, 1 : 2 ]

array([[2],
       [5],
       [8]])

In [10]:
matrix = np . array ([[ 1 , 2 , 3 , 4 ],
                      [ 5 , 6 , 7 , 8 ],
                      [ 9 , 10 , 11 , 12 ]])

print(matrix . shape)
print(matrix . size)
print(matrix . ndim)

(3, 4)
12
2


In [11]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 4 , 5 , 6 ],
                      [ 7 , 8 , 9 ]])
add_100 = lambda i : i + 100
vectorized_add_100 = np . vectorize ( add_100 )
vectorized_add_100 ( matrix )


array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [12]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [13]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 4 , 5 , 6 ],
                      [ 7 , 8 , 9 ]])

print(np . max ( matrix ))

print(np . min ( matrix ))

9
1


In [14]:
print(np . max ( matrix , axis=0 ))

print(np . max ( matrix , axis=1 ))


[7 8 9]
[3 6 9]


In [15]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 4 , 5 , 6 ],
                      [ 7 , 8 , 9 ]])
print(np . mean ( matrix ))

# Return variance
print(np . var ( matrix ))
# Return standard deviation
print(np . std ( matrix ))

5.0
6.666666666666667
2.581988897471611


In [16]:
np . mean ( matrix , axis=0 )

array([4., 5., 6.])

In [18]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 4 , 5 , 6 ],
                      [ 7 , 8 , 9 ],
                      [ 10 , 11 , 12 ]])

print(matrix . reshape ( 2 , 6 ))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [19]:
matrix . size

12

In [20]:
matrix . reshape ( 1 , - 1 )

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [21]:
matrix . reshape ( 12 )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 4 , 5 , 6 ],
                      [ 7 , 8 , 9 ]])
# Transpose matrix
matrix . T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
np . array ([ 1 , 2 , 3 , 4 , 5 , 6 ]) . T

array([1, 2, 3, 4, 5, 6])

In [24]:
np . array ([[ 1 , 2 , 3 , 4 , 5 , 6 ]]) . T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [25]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 4 , 5 , 6 ],
                      [ 7 , 8 , 9 ]])
# Flatten matrix
matrix . flatten ()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
matrix . reshape ( 1 , - 1 )

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
matrix = np . array ([[ 1 , 1 , 1 ],
                      [ 1 , 1 , 10 ],
                      [ 1 , 1 , 15 ]])

print(np . linalg . matrix_rank ( matrix ))

2


In [28]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 2 , 4 , 6 ],
                      [ 3 , 8 , 9 ]])
print(np . linalg . det ( matrix ))

0.0


In [29]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 2 , 4 , 6 ],
                      [ 3 , 8 , 9 ]])

print(matrix . diagonal ())

[1 4 9]


In [31]:
matrix . diagonal ( offset=1 )

print(matrix . diagonal ( offset=- 1 ))

[2 8]


In [32]:
matrix = np . array ([[ 1 , 2 , 3 ],
                      [ 2 , 4 , 6 ],
                      [ 3 , 8 , 9 ]])

print(matrix . trace ())

14


In [34]:
print(sum ( matrix . diagonal ()))

14


In [35]:
vector_a = np . array ([ 1 , 2 , 3 ])
vector_b = np . array ([ 4 , 5 , 6 ])
# Calculate dot product
print(np . dot ( vector_a , vector_b ))

32


In [36]:
print(vector_a @ vector_b)

32


In [37]:
matrix_a = np . array ([[ 1 , 1 , 1 ],
                        [ 1 , 1 , 1 ],
                        [ 1 , 1 , 2 ]])
# Create matrix
matrix_b = np . array ([[ 1 , 3 , 1 ],
                        [ 1 , 3 , 1 ],
                        [ 1 , 3 , 8 ]])
# Add two matrices
print(np . add ( matrix_a , matrix_b ))
print(np . subtract ( matrix_a , matrix_b ))

[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [38]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [39]:
matrix_a = np . array ([[ 1 , 1 ],
                        [ 1 , 2 ]])
# Create matrix
matrix_b = np . array ([[ 1 , 3 ],
                        [ 1 , 2 ]])
# Multiply two matrices
print(np . dot ( matrix_a , matrix_b ))


[[2 5]
 [3 7]]


In [40]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [41]:
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])