<a href="https://colab.research.google.com/github/FRashidy1403/Special/blob/main/rashidy8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4.8

In [2]:
import numpy as np
from sklearn.preprocessing import Binarizer
# Create feature
age = np . array ([[ 6 ],
                   [ 12 ],
                   [ 20 ],
                   [ 36 ],
                   [ 65 ]])
# Create binarizer
binarizer = Binarizer ( threshold=18 )

In [3]:
# Transform feature
binarizer . fit_transform ( age )

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [4]:
# Bin feature
np . digitize ( age , bins= [ 20 , 30 , 64 ])

array([[0],
       [0],
       [1],
       [2],
       [3]])

In [5]:
# Bin feature
np . digitize ( age , bins= [ 20 , 30 , 64 ], right=True )

array([[0],
       [0],
       [0],
       [2],
       [3]])

In [6]:
np . digitize ( age , bins= [ 18 ])

array([[0],
       [0],
       [1],
       [1],
       [1]])

# 4.9

In [7]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

In [8]:
# Make simulated feature matrix
features , _ = make_blobs ( n_samples = 50 ,
                            n_features = 2 ,
                            centers = 3 ,
                            random_state = 1 )
# Create DataFrame
dataframe = pd . DataFrame ( features , columns= [ "feature_1" , "feature_2" ])
# Make k-means clusterer
clusterer = KMeans ( 3 , random_state=0 )

In [9]:
# Fit clusterer
clusterer . fit ( features )
# Predict values
dataframe [ "group" ] = clusterer . predict ( features )
# View first few observations
dataframe . head ( 5 )

feature_1  feature_2  group
0  -9.877554  -3.336145      2
1  -7.287210  -8.353986      0
2  -6.943061  -7.023744      0
3  -7.440167  -8.791959      0
4  -6.641388  -8.075888      0

# 4.10

In [10]:
# Load library
import numpy as np
# Create feature matrix
features = np . array ([[ 1.1 , 11.1 ],
                        [ 2.2 , 22.2 ],
                        [ 3.3 , 33.3 ],
                        [ 4.4 , 44.4 ],
                        [ np . nan , 55 ]])
# Keep only observations that are not (denoted by ~) missing
features [ ~np . isnan ( features ) . any ( axis=1 )]

array([[ 1.1, 11.1],
       [ 2.2, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4]])

In [11]:
# Load data
dataframe = pd . DataFrame ( features , columns= [ "feature_1" , "feature_2" ])
# Remove observations with missing values
dataframe . dropna ()

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

# 4.11

In [12]:
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

In [15]:
# Make a simulated feature matrix
features , _ = make_blobs ( n_samples = 1000 ,
                            n_features = 2 ,
                            random_state = 1 )
# Standardize the features
scaler = StandardScaler ()
standardized_features = scaler . fit_transform ( features )
# Replace the first feature's first value with a missing value
true_value = standardized_features [ 0 , 0 ]
standardized_features [ 0 , 0 ] = np . nan
# Predict the missing values in the feature matrix
knn_imputer = KNNImputer ( n_neighbors=5 )

In [16]:
features_knn_imputed = knn_imputer . fit_transform ( standardized_features )
# Compare true and imputed values
print ( "True Value:" , true_value )
print ( "Imputed Value:" , features_knn_imputed [ 0 , 0 ])

True Value: 0.8730186113995938
Imputed Value: 1.0959262913919632


In [17]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

In [18]:
# Make a simulated feature matrix
features , _ = make_blobs ( n_samples = 1000 ,
                            n_features = 2 ,
                            random_state = 1 )
# Standardize the features
scaler = StandardScaler ()
standardized_features = scaler . fit_transform ( features )
# Replace the first feature's first value with a missing value
true_value = standardized_features [ 0 , 0 ]
standardized_features [ 0 , 0 ] = np . nan
# Create imputer using the "mean" strategy
mean_imputer = SimpleImputer ( strategy= "mean" )
# Impute values
features_mean_imputed = mean_imputer . fit_transform ( features )
# Compare true and imputed values
print ( "True Value:" , true_value )
print ( "Imputed Value:" , features_mean_imputed [ 0 , 0 ])

True Value: 0.8730186113995938
Imputed Value: -3.058372724614996
